<script setup lang="ts">
import { computed, ref } from 'vue'
export type PaddingUnit = 'percent' | 'px'
type Axis = 'horizontal' | 'vertical'
interface Props { imageSrc?: string; imageAlt?: string; horizontalLines: number[]; verticalLines: number[]; padding: number; paddingUnit: PaddingUnit; includeOuter: boolean; expanded: boolean; disabled?: boolean }
const props = withDefaults(defineProps<Props>(), { imageSrc: '', imageAlt: '原图预览', disabled: false })
const emit = defineEmits<{ (e:'update:expanded', value:boolean):void; (e:'update:horizontalLines', value:number[]):void; (e:'update:verticalLines', value:number[]):void; (e:'update:padding', value:number):void; (e:'update:paddingUnit', value:PaddingUnit):void; (e:'update:includeOuter', value:boolean):void }>()
const preview = ref<HTMLElement>(); const selected = ref<{axis:Axis;index:number}|null>(null); const dragging = ref<Axis|null>(null)
const ordered = (lines:number[]) => [...lines].map((line)=>Math.min(99.5,Math.max(.5,Number(line.toFixed(3))))).sort((a,b)=>a-b)
const selectedLabel = computed(() => selected.value ? '删除当前线' : '请选择一条线')
const update = (axis:Axis, lines:number[]) => emit(axis === 'horizontal' ? 'update:horizontalLines' : 'update:verticalLines', ordered(lines))
function addLine(axis:Axis) { const lines = axis === 'horizontal' ? props.horizontalLines : props.verticalLines; const bounds=[0,...ordered(lines),100]; let biggest=0; for(let i=1;i<bounds.length;i+=1) if(bounds[i]-bounds[i-1]>bounds[biggest+1]-bounds[biggest]) biggest=i-1; update(axis,[...lines,(bounds[biggest]+bounds[biggest+1])/2]) }
function removeLine(){ if(!selected.value) return; const lines=selected.value.axis==='horizontal'?props.horizontalLines:props.verticalLines; update(selected.value.axis,lines.filter((_,i)=>i!==selected.value?.index)); selected.value=null }
function start(axis:Axis,index:number,event:PointerEvent){ if(props.disabled) return; selected.value={axis,index}; dragging.value=axis; (event.currentTarget as HTMLElement).setPointerCapture?.(event.pointerId); event.preventDefault() }
function move(event:PointerEvent){ if(!dragging.value||!selected.value||!preview.value) return; const rect=preview.value.getBoundingClientRect(); const value=dragging.value==='horizontal'?(event.clientY-rect.top)/rect.height*100:(event.clientX-rect.left)/rect.width*100; const lines=dragging.value==='horizontal'?props.horizontalLines:props.verticalLines; const next=[...lines]; next[selected.value.index]=value; update(dragging.value,next) }
</script>
<template><section class="panel slice-editor"><button type="button" class="editor-toggle" :aria-expanded="props.expanded" @click="emit('update:expanded',!props.expanded)"><span><span class="eyebrow">裁切参数</span><strong>分割线与边线擦除</strong></span><span>{{ props.expanded ? '收起' : '展开' }}</span></button><div v-if="props.expanded" class="editor-content"><p class="muted">上传前可设置 padding；上传后可拖动、增加或删除分割线。</p><div class="editor-controls"><div><span class="field-label">分割线</span><div class="button-row"><button type="button" :disabled="props.disabled||!props.imageSrc" @click="addLine('horizontal')">+ 横线</button><button type="button" :disabled="props.disabled||!props.imageSrc" @click="addLine('vertical')">+ 竖线</button><button type="button" class="ghost" :disabled="props.disabled||!selected" @click="removeLine">{{ selectedLabel }}</button></div></div><label><span class="field-label">边线擦除</span><div class="padding-control"><input :value="props.padding" type="number" min="0" step="0.1" @input="emit('update:padding',Math.max(0,Number(($event.target as HTMLInputElement).value)||0))" /><button type="button" @click="emit('update:paddingUnit',props.paddingUnit==='px'?'percent':'px')">{{ props.paddingUnit==='px'?'px':'%' }}</button></div></label><label class="outer-toggle"><input :checked="props.includeOuter" type="checkbox" @change="emit('update:includeOuter',($event.target as HTMLInputElement).checked)" />包含图片外边缘</label></div><div v-if="props.imageSrc" ref="preview" class="parameter-preview" @pointermove="move" @pointerup="dragging=null" @pointercancel="dragging=null"><img :src="props.imageSrc" :alt="props.imageAlt" /><button v-for="(position,index) in ordered(props.horizontalLines)" :key="`h-${position}`" type="button" class="line horizontal" :class="{selected:selected?.axis==='horizontal'&&selected.index===index}" :style="{top:`${position}%`}" :aria-label="`横向分割线 ${index+1}`" @pointerdown="start('horizontal',index,$event)" /><button v-for="(position,index) in ordered(props.verticalLines)" :key="`v-${position}`" type="button" class="line vertical" :class="{selected:selected?.axis==='vertical'&&selected.index===index}" :style="{left:`${position}%`}" :aria-label="`纵向分割线 ${index+1}`" @pointerdown="start('vertical',index,$event)" /></div><p v-else class="parameter-empty">上传图片后会在这里显示可拖动的原图分割线。</p></div></section></template>
<style scoped>.editor-toggle{display:flex;width:100%;min-height:36px;align-items:center;justify-content:space-between;border:0;background:transparent;color:inherit;text-align:left;cursor:pointer}.editor-toggle:hover{background:rgb(143 215 202 / .05)}.editor-toggle strong,.editor-toggle .eyebrow{display:block}.editor-content{display:grid;gap:9px;margin-top:9px}.editor-content>.muted{margin:0;font-size:12px}.editor-controls{display:flex;flex-wrap:wrap;gap:10px;align-items:end}.button-row,.padding-control{display:flex;gap:6px;flex-wrap:wrap}.field-label{display:block;margin-bottom:4px;color:#bcd7d1;font-size:12px}.padding-control input{width:78px}.outer-toggle{display:flex;gap:6px;align-items:center;min-height:32px;color:#cbe2dc;font-size:12px}.parameter-preview{position:relative;max-width:520px;overflow:hidden;border-radius:10px;background:#0f1a20;line-height:0;touch-action:none}.parameter-preview img{display:block;width:100%;height:auto}.line{position:absolute;z-index:2;border:0;padding:0;background:transparent}.line::after{position:absolute;content:'';border-radius:999px;background:#47d7ba;box-shadow:0 0 0 1px rgb(0 0 0 / .5)}.horizontal{left:0;width:100%;height:36px;transform:translateY(-50%);cursor:ns-resize}.horizontal::after{top:16px;right:0;left:0;height:3px}.vertical{top:0;width:36px;height:100%;transform:translateX(-50%);cursor:ew-resize}.vertical::after{top:0;bottom:0;left:16px;width:3px}.line.selected::after{background:#f8cc5f}.parameter-empty{margin:0;padding:14px;border:1px dashed rgb(203 239 231 / .18);border-radius:8px;color:#a9c1be}@media(max-width:640px){.editor-controls{display:grid;grid-template-columns:1fr}.parameter-preview{max-width:none}}</style>
