<script setup lang="ts">
import { computed, ref } from 'vue'
type Axis = 'horizontal' | 'vertical'
interface Props { imageSrc?: string; imageAlt?: string; horizontalLines: number[]; verticalLines: number[]; expanded: boolean; disabled?: boolean }
const props = withDefaults(defineProps<Props>(), { imageSrc: '', imageAlt: '原图预览', disabled: false })
const emit = defineEmits<{ (e:'update:expanded', value:boolean):void; (e:'update:horizontalLines', value:number[]):void; (e:'update:verticalLines', value:number[]):void; (e:'confirm', value:{horizontal:number[];vertical:number[]}):void }>()
const preview = ref<HTMLElement>(); const selected = ref<{axis:Axis;index:number}|null>(null); const dragging = ref<Axis|null>(null)
const draftLines = ref<Record<Axis, number[]>>({ horizontal: [], vertical: [] }); const hasDraft = ref(false); const movedDuringDrag = ref(false)
const ordered = (lines:number[]) => [...lines].map((line)=>Math.min(99.5,Math.max(.5,Number(line.toFixed(3))))).sort((a,b)=>a-b)
const selectedLabel = computed(() => selected.value ? '删除当前线' : '请选择一条线')
const propLines = (axis: Axis) => ordered(axis === 'horizontal' ? props.horizontalLines : props.verticalLines)
const syncDraft = () => { draftLines.value = { horizontal: propLines('horizontal'), vertical: propLines('vertical') } }
const linesFor = (axis: Axis) => hasDraft.value || dragging.value ? draftLines.value[axis] : propLines(axis)
const clampLinePosition = (value: number, lower: number, upper: number) =>
  Number(Math.min(upper, Math.max(lower, value)).toFixed(3))
function addLine(axis:Axis) { if(!hasDraft.value) syncDraft(); const lines=draftLines.value[axis]; const bounds=[0,...ordered(lines),100]; let biggest=0; for(let i=1;i<bounds.length;i+=1) if(bounds[i]-bounds[i-1]>bounds[biggest+1]-bounds[biggest]) biggest=i-1; const next=ordered([...lines,(bounds[biggest]+bounds[biggest+1])/2]); draftLines.value[axis]=next; selected.value={axis,index:next.indexOf((bounds[biggest]+bounds[biggest+1])/2)}; hasDraft.value=true }
function removeLine(){ if(!selected.value) return; if(!hasDraft.value) syncDraft(); const axis=selected.value.axis; draftLines.value[axis]=draftLines.value[axis].filter((_,i)=>i!==selected.value?.index); hasDraft.value=true; selected.value=null }
function start(axis:Axis,index:number,event:PointerEvent){ if(props.disabled) return; if(!hasDraft.value) syncDraft(); selected.value={axis,index}; dragging.value=axis; movedDuringDrag.value=false; (event.currentTarget as HTMLElement).setPointerCapture?.(event.pointerId); event.preventDefault() }
function move(event:PointerEvent){ if(!dragging.value||!selected.value||!preview.value) return; const axis=dragging.value; const rect=preview.value.getBoundingClientRect(); const value=axis==='horizontal'?(event.clientY-rect.top)/rect.height*100:(event.clientX-rect.left)/rect.width*100; const lines=[...draftLines.value[axis]]; const index=selected.value.index; const lower=index === 0 ? .5 : lines[index-1]+.5; const upper=index === lines.length-1 ? 99.5 : lines[index+1]-.5; const next=clampLinePosition(value,lower,upper); movedDuringDrag.value ||= lines[index] !== next; lines[index]=next; draftLines.value[axis]=lines }
function commitDrag(){ if(!dragging.value) return; if(movedDuringDrag.value) hasDraft.value=true; dragging.value=null }
function cancelDrag(){ dragging.value=null; movedDuringDrag.value=false }
function restoreDraft(){ syncDraft(); hasDraft.value=false; selected.value=null }
function confirmDraft(){ if(!hasDraft.value) return; emit('confirm',{ horizontal: ordered(draftLines.value.horizontal), vertical: ordered(draftLines.value.vertical) }); hasDraft.value=false }
</script>
<template><section class="panel slice-editor"><button type="button" class="editor-toggle" :aria-expanded="props.expanded" @click="emit('update:expanded',!props.expanded)"><span><span class="eyebrow">裁切参数</span><strong>分割线编辑</strong></span><span>{{ props.expanded ? '收起' : '展开' }}</span></button><div v-if="props.expanded" class="editor-content"><p class="muted">上传后可拖动、增加或删除分割线。</p><div class="editor-controls"><div><span class="field-label">分割线</span><div class="button-row"><button type="button" :disabled="props.disabled||!props.imageSrc" @click="addLine('horizontal')">+ 横线</button><button type="button" :disabled="props.disabled||!props.imageSrc" @click="addLine('vertical')">+ 竖线</button><button type="button" class="ghost" :disabled="props.disabled||!selected" @click="removeLine">{{ selectedLabel }}</button></div></div></div><div v-if="props.imageSrc" ref="preview" class="parameter-preview" @pointermove="move" @pointerup="commitDrag" @pointercancel="cancelDrag"><img :src="props.imageSrc" :alt="props.imageAlt" /><button v-for="(position,index) in linesFor('horizontal')" :key="`h-${index}`" type="button" class="line horizontal" :class="{selected:selected?.axis==='horizontal'&&selected.index===index}" :style="{top:`${position}%`}" :aria-label="`横向分割线 ${index+1}`" @pointerdown="start('horizontal',index,$event)" @lostpointercapture="commitDrag" /><button v-for="(position,index) in linesFor('vertical')" :key="`v-${index}`" type="button" class="line vertical" :class="{selected:selected?.axis==='vertical'&&selected.index===index}" :style="{left:`${position}%`}" :aria-label="`纵向分割线 ${index+1}`" @pointerdown="start('vertical',index,$event)" @lostpointercapture="commitDrag" /></div><div v-if="hasDraft" class="draft-actions"><span class="muted">分割线修改尚未裁切</span><button data-testid="restore-line-draft" type="button" class="ghost" :disabled="props.disabled" @click="restoreDraft">恢复</button><button data-testid="confirm-line-draft" type="button" :disabled="props.disabled" @click="confirmDraft">确认并裁切</button></div><p v-if="!props.imageSrc" class="parameter-empty">上传图片后会在这里显示可拖动的原图分割线。</p></div></section></template>
<style scoped>.editor-toggle{display:flex;width:100%;min-height:36px;align-items:center;justify-content:space-between;border:0;background:transparent;color:inherit;text-align:left;cursor:pointer}.editor-toggle:hover{background:rgb(143 215 202 / .05)}.editor-toggle strong,.editor-toggle .eyebrow{display:block}.editor-content{display:grid;min-width:0;gap:9px;margin-top:9px}.editor-content>.muted{margin:0;font-size:12px}.editor-controls{display:flex;flex-wrap:wrap;gap:10px;align-items:end}.button-row{display:flex;gap:6px;flex-wrap:wrap}.field-label{display:block;margin-bottom:4px;color:#bcd7d1;font-size:12px}.parameter-preview{position:relative;max-width:520px;overflow:hidden;border-radius:10px;background:#0f1a20;line-height:0;touch-action:none}.parameter-preview img{display:block;max-width:100%;width:100%;height:auto}.line{position:absolute;z-index:2;border:0;padding:0;background:transparent}.line::after{position:absolute;content:'';border-radius:999px;background:#47d7ba;box-shadow:0 0 0 1px rgb(0 0 0 / .5)}.horizontal{left:0;width:100%;height:36px;transform:translateY(-50%);cursor:ns-resize}.horizontal::after{top:16px;right:0;left:0;height:3px}.vertical{top:0;width:36px;height:100%;transform:translateX(-50%);cursor:ew-resize}.vertical::after{top:0;bottom:0;left:16px;width:3px}.line.horizontal:hover,.line.horizontal:active:not(:disabled){transform:translateY(-50%)}.line.vertical:hover,.line.vertical:active:not(:disabled){transform:translateX(-50%)}.line.selected::after{background:#f8cc5f}.draft-actions{display:flex;flex-wrap:wrap;align-items:center;gap:6px}.draft-actions .muted{margin-right:auto;font-size:12px}.parameter-empty{margin:0;padding:14px;border:1px dashed rgb(203 239 231 / .18);border-radius:8px;color:#a9c1be}@media(max-width:640px){.parameter-preview{width:100%;max-width:100%;min-width:0}}</style>
